config/routes.rb
SchoolTweets::Application.routes.draw do

  resources :schools, only: [:index, :show]
  match 'tweet_maps' => 'tweet_maps#index'
  match 'tweets' => 'tweets#show'
  root :to => 'tweet_maps#index'

end

app/models/school.rb
class School < ActiveRecord::Base
  attr_accessible :isbe
end

app/models/tweet.rb
class Tweet
  attr_reader :screen_name, :text, :created_at
  def initialize options
    @screen_name = options[:screen_name]
    @text = options[:text]
    @created_at = options[:created_at]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  respond_to :html, :json
  def index
    @schools = School.order("name").all
    respond_with @schools
  end

  def show
    @school = School.find params[:id]
    @tweets = TwitterService.new.get_tweets_for(@school, "school")
  end
end

app/controllers/tweet_maps_controller.rb
class TweetMapsController < ApplicationController
  def index
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  respond_to :json
  def show
    school = School.find_by_isbe params[:isbe]
    tweets = school.present? ? TwitterService.new.get_tweets_for(school, 'school') : []
    respond_with tweets
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolTweets</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

    <script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=<%= GOOGLE_API_KEY %>&sensor=false">
    </script>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/schools/index.html.erb
<ul>
  <% @schools.each do |school| %>
    <li>
      <%= link_to school.name, school_url(school) %>
    </li>
  <% end %>
</ul>

app/views/schools/show.html.erb
<%= @school.name %>
<ul>
  <% @tweets.each do |tweet| %>
    <li>
      <div>At <%= tweet.created_at.strftime('%B %d, %Y %l:%M%p') %>, <%= tweet.screen_name %> said:</div>
      <div><%= tweet.text %></div>
    </li>
  <% end %>
</ul>

app/views/tweet_maps/index.html.erb
<div id='map_canvas' style='width: 100%; height:100%'></div>